jsonStr_MM = [
    {"name":"အာဖဂန်နစ္စတန်","code":"AF"},
    {"name":"Aland ကျွန်းများ","code":"AX"},
    {"name":"အယ်လ်ဘေးနီးယား","code":"AL"},
    {"name":"အယ်လ်ဂျီးရီးယား","code":"DZ"},
    {"name":"အမေရိကန်ဆာမိုအာ","code":"AS"},
    {"name":"အန်ဒိုရာ","code":"AD"},
    {"name":"အင်ဂိုလာ","code":"AO"},
    {"name":"Anguilla","code":"AI"},
    {"name":"အန္တာတိကတိုက်","code":"AQ"},
    {"name":"Antigua နှင့် Barbuda","code":"AG"},
    {"name":"အာဂျင်တီးနား","code":"AR"},
    {"name":"အာမေးနီးယား","code":"AM"},
    {"name":"Aruba","code":"AW"},
    {"name":"သြစတြေးလျ","code":"AU"},
    {"name":"သြစတြီးယား","code":"AT"},
    {"name":"အဇာဘိုင်ဂျန်","code":"AZ"},
    {"name":"ဘဟားမား","code":"BS"},
    {"name":"ဘာရိန်း","code":"BH"},
    {"name":"ဘင်္ဂလားဒေ့ရှ်","code":"BD"},
    {"name":"ဘာဘေးဒိုးစ်","code":"BB"},
    {"name":"ဘီလာရုစ်","code":"BY"},
    {"name":"ဘယ်လ်ဂျီယံ","code":"BE"},
    {"name":"ဘေလီဇ်","code":"BZ"},
    {"name":"ဘီနင်","code":"BJ"},
    {"name":"ဘာမြူဒါ","code":"BM"},
    {"name":"ဘူတန်","code":"BT"},
    {"name":"ဘိုလီးဗီးယား","code":"BO"},
    {"name":"Bonaire, Sint Eustatius နှင့် Saba တို့ဖြစ်သည်","code":"BQ"},
    {"name":"ဘော့စနီးယားနှင့်ဟာဇီဂိုဗီးနား","code":"BA"},
    {"name":"ဘော့ဆွာနာ","code":"BW"},
    {"name":"Bouvet ကျွန်း","code":"BV"},
    {"name":"ဘရာဇီး","code":"BR"},
    {"name":"ဗြိတိသျှအိန္ဒိယသမုဒ္ဒရာနယ်မြေ","code":"IO"},
    {"name":"ဘရူနိုင်း Darussalam","code":"BN"},
    {"name":"ဘူဂေးရီးယား","code":"BG"},
    {"name":"Burkina Faso","code":"BF"},
    {"name":"ဘူရွန်ဒီ","code":"BI"},
    {"name":"ကမ္ဘောဒီးယား","code":"KH"},
    {"name":"ကင်မရွန်း","code":"CM"},
    {"name":"ကနေဒါ","code":"CA"},
    {"name":"ကိပ် Verde","code":"CV"},
    {"name":"ကေမန်ကျွန်းစု","code":"KY"},
    {"name":"ဗဟိုအာဖရိကသမ္မတနိုင်ငံ","code":"CF"},
    {"name":"ချဒ်","code":"TD"},
    {"name":"ချီလီ","code":"CL"},
    {"name":"တရုတ်","code":"CN"},
    {"name":"ခရစ်စမတ်ကျွန်း","code":"CX"},
    {"name":"ကိုကို (ကီလင်) ကျွန်းများ","code":"CC"},
    {"name":"ကိုလံဘီယာ","code":"CO"},
    {"name":"Comoros","code":"KM"},
    {"name":"ကွန်ဂို","code":"CG"},
    {"name":"ကွန်ဂိုဒီမိုကရက်တစ်သမ္မတနိုင်ငံ","code":"CD"},
    {"name":"ကွတ်ကျွန်းများ","code":"CK"},
    {"name":"ကော့စတာရီကာ","code":"CR"},
    {"name":"Cote D'Ivoire","code":"CI"},
    {"name":"ခရိုအေးရှား","code":"HR"},
    {"name":"ကျူးဘား","code":"CU"},
    {"name":"ကရာကေး","code":"CW"},
    {"name":"ဆိုက်ပရပ်စ်","code":"CY"},
    {"name":"ချက်သမ္မတနိုင်ငံ","code":"CZ"},
    {"name":"ဒိန်းမတ်","code":"DK"},
    {"name":"ဂျီဘူတီ","code":"DJ"},
    {"name":"ဒိုမီနီကာ","code":"DM"},
    {"name":"ဒိုမီနီကန်သမ္မတနိုင်ငံ","code":"DO"},
    {"name":"အီကွေဒေါ","code":"EC"},
    {"name":"အီဂျစ်","code":"EG"},
    {"name":"အယ်လ်ဆာဗေးဒေါ","code":"SV"},
    {"name":"အီကွေတာဂီနီ","code":"GQ"},
    {"name":"အီရီထရီးယား","code":"ER"},
    {"name":"အက်စ်တိုးနီးယား","code":"EE"},
    {"name":"အီသီယိုးပီးယား","code":"ET"},
    {"name":"ဖalklandကျွန်းများ (Malvinas)","code":"FK"},
    {"name":"ဖာရိုးကျွန်းများ","code":"FO"},
    {"name":"ဖီဂျီ","code":"FJ"},
    {"name":"ဖင်လန်","code":"FI"},
    {"name":"ပြင်သစ်","code":"FR"},
    {"name":"ပြင်သစ်ဂူယာနာ","code":"GF"},
    {"name":"ပြင်သစ်ပိုလီနီးရှား","code":"PF"},
    {"name":"ပြင်သစ်တောင်ပိုင်းနယ်မြေများ","code":"TF"},
    {"name":"ဂါဘွန်း","code":"GA"},
    {"name":"ဂမ်ဘီယာ","code":"GM"},
    {"name":"ဂျော်ဂျီယာ","code":"GE"},
    {"name":"ဂျာမနီ","code":"DE"},
    {"name":"ဂါနာ","code":"GH"},
    {"name":"ဂျီဘရောလ်","code":"GI"},
    {"name":"ဂရိ","code":"GR"},
    {"name":"ဂရင်းလန်း","code":"GL"},
    {"name":"ဂရီနာဒါ","code":"GD"},
    {"name":"ဂွာတီလူး","code":"GP"},
    {"name":"ဂူအမ်","code":"GU"},
    {"name":"ဂွာတီမာလာ","code":"GT"},
    {"name":"Guernsey","code":"GG"},
    {"name":"ဂီနီယာ","code":"GN"},
    {"name":"ဂီနီ -bissau","code":"GW"},
    {"name":"ဂိုင်ယာနာ","code":"GY"},
    {"name":"ဟေတီ","code":"HT"},
    {"name":"ဟတ်ကျွန်းနှင့်မက်ဒေါ်နယ်ကျွန်းများ","code":"HM"},
    {"name":"သန့်ရှင်းသောဘုရား (ဗာတီကန်စီးတီးပြည်နယ်)","code":"VA"},
    {"name":"ဟွန်ဒူးရပ်စ်","code":"HN"},
    {"name":"ဟောင်ကောင်","code":"HK"},
    {"name":"ဟန်ဂေရီ","code":"HU"},
    {"name":"အိုက်စလန်","code":"IS"},
    {"name":"အိန္ဒိယ","code":"IN"},
    {"name":"အင်ဒိုနီးရှား","code":"ID"},
    {"name":"အီရန်, အစ္စလာမ်မစ်သမ္မတနိုင်ငံ","code":"IR"},
    {"name":"အီရတ်","code":"IQ"},
    {"name":"အိုင်ယာလန်","code":"IE"},
    {"name":"Man of Isle","code":"IM"},
    {"name":"အစ္စရေး","code":"IL"},
    {"name":"အီတလီ","code":"IT"},
    {"name":"ဂျမေကာ","code":"JM"},
    {"name":"ဂျပန်","code":"JP"},
    {"name":"ဂျာစီ","code":"JE"},
    {"name":"ဂျော်ဒန်","code":"JO"},
    {"name":"ကာဇက်စတန်","code":"KZ"},
    {"name":"ကင်ညာ","code":"KE"},
    {"name":"ကီရီဘာတီ","code":"KI"},
    {"name":"ကိုရီးယား၊ ဒီမိုကရက်တစ်ပြည်သူ့သမ္မတနိုင်ငံ","code":"KP"},
    {"name":"ကိုရီးယားသမ္မတနိုင်ငံ","code":"KR"},
    {"name":"ကိုဆိုဗို","code":"XK"},
    {"name":"ကူဝိတ်","code":"KW"},
    {"name":"ကာဂျစ္စတန်","code":"KG"},
    {"name":"လာအိုပြည်သူ့ဒီမိုကရက်တစ်သမ္မတနိုင်ငံ","code":"LA"},
    {"name":"လတ်ဗီးယား","code":"LV"},
    {"name":"လက်ဘနွန်","code":"LB"},
    {"name":"လီဆိုသို","code":"LS"},
    {"name":"လိုက်ဘေးရီးယား","code":"LR"},
    {"name":"လစ်ဗျားအာရပ် Jamahiriya","code":"LY"},
    {"name":"Liechtenstein","code":"LI"},
    {"name":"လစ်သူယေးနီးယား","code":"LT"},
    {"name":"လူဇင်ဘတ်","code":"LU"},
    {"name":"မကာအို","code":"MO"},
    {"name":"မက်ဆီဒိုးနီးယား၏ယခင်ယူဂိုဆလားဗီးယားသမ္မတနိုင်ငံ","code":"MK"},
    {"name":"မာဒါဂက်စကာ","code":"MG"},
    {"name":"မာလာဝီ","code":"MW"},
    {"name":"မလေးရှား","code":"MY"},
    {"name":"မော်လ်ဒိုက်","code":"MV"},
    {"name":"မာလီ","code":"ML"},
    {"name":"မော်လတာ","code":"MT"},
    {"name":"မာရှယ်ကျွန်းစု","code":"MH"},
    {"name":"Martinique","code":"MQ"},
    {"name":"Mauritania","code":"MR"},
    {"name":"Mauritius","code":"MU"},
    {"name":"Mayotte","code":"YT"},
    {"name":"မက္ကစီကို","code":"MX"},
    {"name":"မီခရိုနီးရှား၊","code":"FM"},
    {"name":"မော်လ်ဒိုဗာ, သမ္မတနိုင်ငံ","code":"MD"},
    {"name":"မိုနာကို","code":"MC"},
    {"name":"မွန်ဂိုလီးယား","code":"MN"},
    {"name":"မွန်တီနီဂရိုး","code":"ME"},
    {"name":"မွန်ဆာရတ်","code":"MS"},
    {"name":"မော်ရိုကို","code":"MA"},
    {"name":"မိုဇမ်ဘစ်","code":"MZ"},
    {"name":"မြန်မာ","code":"MM"},
    {"name":"နမီးဘီးယား","code":"NA"},
    {"name":"Nauru","code":"NR"},
    {"name":"နီပေါ","code":"NP"},
    {"name":"နယ်သာလန်","code":"NL"},
    {"name":"နယ်သာလန်အန်တီ","code":"AN"},
    {"name":"နယူးကယ်လီဒိုးနီးယား","code":"NC"},
    {"name":"နယူးဇီလန်","code":"NZ"},
    {"name":"နီကာရာဂွာ","code":"NI"},
    {"name":"နိုင်ဂျာ","code":"NE"},
    {"name":"နိုင်ဂျီးရီးယား","code":"NG"},
    {"name":"နီယို","code":"NU"},
    {"name":"-Norfolk ကျွန်း","code":"NF"},
    {"name":"မြောက်ပိုင်းမာရီယာနာကျွန်းများ","code":"MP"},
    {"name":"နော်ဝေး","code":"NO"},
    {"name":"အိုမန်","code":"OM"},
    {"name":"ပါကစ္စတန်","code":"PK"},
    {"name":"ပလောင်","code":"PW"},
    {"name":"ပါလက်စတိုင်းနယ်မြေ, သိမ်းပိုက်","code":"PS"},
    {"name":"ပနားမား","code":"PA"},
    {"name":"ပါပူဝါနယူးဂီနီ","code":"PG"},
    {"name":"ပါရာဂွေး","code":"PY"},
    {"name":"ပီရူး","code":"PE"},
    {"name":"ဖိလစ်ပိုင်","code":"PH"},
    {"name":"Pitcairn","code":"PN"},
    {"name":"ပိုလန်","code":"PL"},
    {"name":"ပေါ်တူဂီ","code":"PT"},
    {"name":"Puerto Rico","code":"PR"},
    {"name":"ကာတာ","code":"QA"},
    {"name":"ပြန်လည်ပေါင်းစည်းခြင်း","code":"RE"},
    {"name":"ရိုမေးနီးယား","code":"RO"},
    {"name":"ရုရှားပြည်ထောင်စု","code":"RU"},
    {"name":"ရဝမ်ဒါ","code":"RW"},
    {"name":"Saint Barthelemy","code":"BL"},
    {"name":"စိန့်ဟယ်လီနာ","code":"SH"},
    {"name":"စိန့်ကစ်နှင့်နီဗီစ်","code":"KN"},
    {"name":"စိန့်လူစီယာ","code":"LC"},
    {"name":"စိန့်မာတင်","code":"MF"},
    {"name":"စိန့် Pierre နှင့် Miquelon","code":"PM"},
    {"name":"စိန့်ဗင်းဆင့်နှင့်ဂရီနာဒင်းများ","code":"VC"},
    {"name":"ဆာမိုအာ","code":"WS"},
    {"name":"စန်မာရီနို","code":"SM"},
    {"name":"Sao Tome နှင့် Principe","code":"ST"},
    {"name":"ဆော်ဒီအာရေဗျ","code":"SA"},
    {"name":"ဆီနီဂေါ","code":"SN"},
    {"name":"ဆားဘီးယား","code":"RS"},
    {"name":"ဆားဘီးယားနှင့်မွန်တီနီဂရိုး","code":"CS"},
    {"name":"Seychelles","code":"SC"},
    {"name":"ဆီးရီးယားလီယွန်း","code":"SL"},
    {"name":"စင်္ကာပူ","code":"SG"},
    {"name":"စိန့်မာတင်","code":"SX"},
    {"name":"စလိုဗက်ကီးယား","code":"SK"},
    {"name":"ဆလိုဗေးနီးယား","code":"SI"},
    {"name":"ဆော်လမွန်ကျွန်းစု","code":"SB"},
    {"name":"ဆိုမာလီယာ","code":"SO"},
    {"name":"တောင်အာဖရိက","code":"ZA"},
    {"name":"တောင်ပိုင်းဂျော်ဂျီယာနှင့်တောင်ပိုင်း Sandwich ကကျွန်းများ","code":"GS"},
    {"name":"တောင်ဆူဒန်","code":"SS"},
    {"name":"စပိန်","code":"ES"},
    {"name":"သီရိလင်္ကာ","code":"LK"},
    {"name":"ဆူဒန်","code":"SD"},
    {"name":"ဆူရီနာ","code":"SR"},
    {"name":"Svalbard နှင့်ဇန်နဝါရီ Mayen","code":"SJ"},
    {"name":"ဆွာဇီလန်","code":"SZ"},
    {"name":"ဆွီဒင်နိုင်ငံ","code":"SE"},
    {"name":"ဆွစ်ဇာလန်","code":"CH"},
    {"name":"ဆီးရီးယားအာရပ်သမ္မတနိုင်ငံ","code":"SY"},
    {"name":"ထိုင်ဝမ်, တရုတ်","code":"TW"},
    {"name":"တာဂျစ်ကစ္စတန်","code":"TJ"},
    {"name":"တန်ဇန်းနီးယား, ယူနိုက်တက်သမ္မတနိုင်ငံ","code":"TZ"},
    {"name":"ထိုင်းနိုင်ငံ","code":"TH"},
    {"name":"တီမော - လက်စ်တီ","code":"TL"},
    {"name":"သွားရန်","code":"TG"},
    {"name":"တိုကျို","code":"TK"},
    {"name":"Tonga","code":"TO"},
    {"name":"ထရီနီဒက်နှင့်တိုဘာဂို","code":"TT"},
    {"name":"တူနီးရှား","code":"TN"},
    {"name":"ကြက်ဆင်","code":"TR"},
    {"name":"Turkmenistan","code":"TM"},
    {"name":"တူရကီနှင့် Caicos ကျွန်းများ","code":"TC"},
    {"name":"တူဗာလူ","code":"TV"},
    {"name":"ယူဂန်ဒါ","code":"UG"},
    {"name":"ယူကရိန်း","code":"UA"},
    {"name":"ယူအေအီး","code":"AE"},
    {"name":"ယူနိုက်တက်ကင်းဒမ်း","code":"GB"},
    {"name":"အမေရိကန်","code":"US"},
    {"name":"ယူနိုက်တက်စတိတ်မိုင်းနားကျွန်းများ","code":"UM"},
    {"name":"ဥရုဂွေး","code":"UY"},
    {"name":"ဥဇဘက်ကစ္စတန်","code":"UZ"},
    {"name":"ဗနူတူး","code":"VU"},
    {"name":"ဗင်နီဇွဲလား","code":"VE"},
    {"name":"ဗီယက်နမ်","code":"VN"},
    {"name":"ဗာဂျင်းကျွန်းစုများ၊","code":"VG"},
    {"name":"ဗာဂျင်းကျွန်းများ, U.s.","code":"VI"},
    {"name":"Wallis နှင့် Futuna","code":"WF"},
    {"name":"အနောက်ပိုင်းဆာဟာရ","code":"EH"},
    {"name":"ယီမင်","code":"YE"},
    {"name":"ဇမ်ဘီယာ","code":"ZM"},
    {"name":"ဇင်ဘာဘွေ","code":"ZW"}
];